export const CONSTRUCTOR_ADD_ITEM: 'CONSTRUCTOR_ADD_ITEM' = 'CONSTRUCTOR_ADD_ITEM';
export const CONSTRUCTOR_DELETE_ITEM: 'CONSTRUCTOR_DELETE_ITEM' = 'CONSTRUCTOR_DELETE_ITEM';
export const CONSTRUCTOR_SORT: 'CONSTRUCTOR_SORT' = 'CONSTRUCTOR_SORT';
export const CONSTRUCTOR_RESET: 'CONSTRUCTOR_RESET' = 'CONSTRUCTOR_RESET';