export const CREATE_NEW_ORDER_REQUEST: 'CREATE_NEW_ORDER_REQUEST' = 'CREATE_NEW_ORDER_REQUEST';
export const CREATE_NEW_ORDER_FAILED: 'CREATE_NEW_ORDER_FAILED' = 'CREATE_NEW_ORDER_FAILED';
export const CREATE_NEW_ORDER_SUCCESS: 'CREATE_NEW_ORDER_SUCCESS' = 'CREATE_NEW_ORDER_SUCCESS';
export const RESET_ORDER: 'RESET_ORDER' = 'RESET_ORDER';