export const REGISTRATION_REQUEST: 'REGISTRATION_REQUEST' = 'REGISTRATION_REQUEST';
export const REGISTRATION_FAILED: 'REGISTRATION_FAILED' = 'REGISTRATION_FAILED';
export const REGISTRATION_SUCCESS: 'REGISTRATION_SUCCESS' = 'REGISTRATION_SUCCESS';

export const LOGIN_REQUEST: 'LOGIN_REQUEST' = 'LOGIN_REQUEST';
export const LOGIN_FAILED: 'LOGIN_FAILED' = 'LOGIN_FAILED';
export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS';

export const LOGIN_FORM_SET_VALUE: 'LOGIN_FORM_SET_VALUE' = 'LOGIN_FORM_SET_VALUE';
export const PROFILE_FORM_SET_VALUE: 'PROFILE_FORM_SET_VALUE' = 'PROFILE_FORM_SET_VALUE';
export const REGISTRATION_FORM_SET_VALUE: "REGISTRATION_FORM_SET_VALUE" = "REGISTRATION_FORM_SET_VALUE";
export const PASSWORD_FORGOT_FORM_SET_VALUE: "PASSWORD_FORGOT_FORM_SET_VALUE" = "PASSWORD_FORGOT_FORM_SET_VALUE";
export const PASSWORD_RESET_FORM_SET_VALUE: "PASSWORD_RESET_FORM_SET_VALUE" = "PASSWORD_RESET_FORM_SET_VALUE";

export const USER_INFO_REQUEST: "USER_INFO_REQUEST" = "USER_INFO_REQUEST";
export const USER_INFO_SUCCESS: "USER_INFO_SUCCESS" = "USER_INFO_SUCCESS";
export const USER_INFO_FAILED: "USER_INFO_FAILED" = "USER_INFO_FAILED";

export const USER_INFO_PATCH_REQUEST: "USER_INFO_PATCH_REQUEST" = "USER_INFO_PATCH_REQUEST";
export const USER_INFO_PATCH_SUCCESS: "USER_INFO_PATCH_SUCCESS" = "USER_INFO_PATCH_SUCCESS";
export const USER_INFO_PATCH_FAILED: "USER_INFO_PATCH_FAILED" = "USER_INFO_PATCH_FAILED";

export const FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST" = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS" = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILED: "FORGOT_PASSWORD_FAILED" = "FORGOT_PASSWORD_FAILED";

export const RESET_PASSWORD_REQUEST: "RESET_PASSWORD_REQUEST" = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS" = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILED: "RESET_PASSWORD_FAILED" = "RESET_PASSWORD_FAILED";

export const USER_LOGOUT: "USER_LOGOUT" = "USER_LOGOUT";